version: "3.8" # (Optional) Remove version if you are using docker-compose v2.x or higher
volumes:
  mongodb:
    driver: local
  postgres-volume:
    driver: local
  rabbitmq_data:
    driver: local
  minio_data:
    driver: local

services:
  postgres-sesi-senai:
    image: postgres:16
    container_name: postgres-sesi-senai
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-sesi_senai}
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sesi-senai

  mongodb-sesi-senai:
    image: mongo:7.0.5
    container_name: mongodb-sesi-senai
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-financial-internal}
    networks:
      - sesi-senai

  nginx-sesi-senai:
    image: nginx:latest
    container_name: nginx-sesi-senai
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - main-frontend
      - main-backend
      - main-backend-2
    networks:
      - sesi-senai

  main-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: main-frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - sesi-senai

  main-backend:
    build:
      context: ./backend/java/ava_senai
      dockerfile: Dockerfile
    container_name: main-backend
    volumes:
      - ./backend/java/ava_senai:/app
    ports:
      - "9000:8080"
    depends_on:
      - postgres-sesi-senai
      - mongodb-sesi-senai
    networks:
      - sesi-senai

  main-backend-2:
    build:
      context: ./backend/java/ava_senai
      dockerfile: Dockerfile
    container_name: main-backend-2
    volumes:
      - ./backend/java/ava_senai:/app
    ports:
      - "9009:8080"
    depends_on:
      - postgres-sesi-senai
      - mongodb-sesi-senai
    networks:
      - sesi-senai

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: ava-rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - sesi-senai

  minio:
    image: minio/minio:latest
    ports:
      - "9191:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - sesi-senai

networks:
  sesi-senai:
    driver: bridge
